CREATE TABLE post (  
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    name VARCHAR(250) NOT NULL,
    content VARCHAR(500),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);