/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Lee Zhen Yong (bruceoutdoors@gmail.com)
 */
public class ViewPostDialog extends javax.swing.JDialog {

    private int mId;
    /**
     * Creates new form ViewPostDialog
     */
    public ViewPostDialog(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        commentPanel.setLayout(new BoxLayout(commentPanel, BoxLayout.Y_AXIS));

        setPostId(id);
    }
    
    public void setPostId(int id) {
        try {
            mId = id;
            String sql = "SELECT * FROM post WHERE id = " + Integer.toString(id);
            ResultSet rs = core.DB.getInstance().executeQuery(sql);
            rs.next();
            titleLbl.setText(rs.getString("title"));
            nameLbl.setText("Written by " + rs.getString("name") + " (" +
                    new SimpleDateFormat("dd MMMM yyyy, h:mma").format(rs.getTimestamp("date_created")) + ")");
            contentAreaTxt.setText(rs.getString("content"));
            
            commentPanel.removeAll();
            sql = "SELECT * FROM comment WHERE post_id = " + Integer.toString(id);
            rs = core.DB.getInstance().executeQuery(sql);
            
            while(rs.next()) {
                String dStr = new SimpleDateFormat("dd-MM-yyyy HH:mm").format(rs.getTimestamp("date_created"));
                addPost(rs.getString("name"),
                        rs.getString("comment"),
                        dStr
                );
            }
            
            validate();
        } catch (SQLException ex) {
            Logger.getLogger(ViewPostDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void addPost(String name, String content, String dateCreated) {
        JTextArea contentTxtArea = new JTextArea(content);
        contentTxtArea.setWrapStyleWord(true);
        contentTxtArea.setLineWrap(true);
        contentTxtArea.setEditable(false);

        JPanel leftAlignPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel auth = new JLabel("Comment by " + name + " (" + dateCreated + ")");
        leftAlignPanel.add(auth);

        commentPanel.add(leftAlignPanel);
        commentPanel.add(contentTxtArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentAreaTxt = new javax.swing.JTextArea();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentPanel = new javax.swing.JPanel();
        addCommentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contentAreaTxt.setEditable(false);
        contentAreaTxt.setColumns(20);
        contentAreaTxt.setLineWrap(true);
        contentAreaTxt.setRows(5);
        contentAreaTxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(contentAreaTxt);

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setText("Title of Micropost");

        nameLbl.setText("By Lee Zhen Yong");
        nameLbl.setAlignmentX(1.0F);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Comments:");

        javax.swing.GroupLayout commentPanelLayout = new javax.swing.GroupLayout(commentPanel);
        commentPanel.setLayout(commentPanelLayout);
        commentPanelLayout.setHorizontalGroup(
            commentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        commentPanelLayout.setVerticalGroup(
            commentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(commentPanel);

        addCommentBtn.setText("Add Comment");
        addCommentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addCommentBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCommentBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCommentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentBtnActionPerformed
        new AddCommentDialog(this, true, mId).setVisible(true);
        setPostId(mId);
    }//GEN-LAST:event_addCommentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCommentBtn;
    private javax.swing.JPanel commentPanel;
    private javax.swing.JTextArea contentAreaTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
